// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADK_l9_hFaNwoyMSvFL7wvNOlYGCRbfZ0',
    appId: '1:412192105999:web:df2c9a9def2de3a355e57a',
    messagingSenderId: '412192105999',
    projectId: 'projetflutter-2860b',
    authDomain: 'projetflutter-2860b.firebaseapp.com',
    storageBucket: 'projetflutter-2860b.firebasestorage.app',
    measurementId: 'G-DLWZ3PNVTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49-Cik5xdEYAYDBQHGB2sbX3612PTHf4',
    appId: '1:412192105999:android:5645190b25b6ade155e57a',
    messagingSenderId: '412192105999',
    projectId: 'projetflutter-2860b',
    storageBucket: 'projetflutter-2860b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBemqX6NqTTNOd7BGhlegWzy32snRiTaQ',
    appId: '1:412192105999:ios:7f402985c614bd4e55e57a',
    messagingSenderId: '412192105999',
    projectId: 'projetflutter-2860b',
    storageBucket: 'projetflutter-2860b.firebasestorage.app',
    iosBundleId: 'com.example.projetmouhamadoumoustaphadioufl3gl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBemqX6NqTTNOd7BGhlegWzy32snRiTaQ',
    appId: '1:412192105999:ios:7f402985c614bd4e55e57a',
    messagingSenderId: '412192105999',
    projectId: 'projetflutter-2860b',
    storageBucket: 'projetflutter-2860b.firebasestorage.app',
    iosBundleId: 'com.example.projetmouhamadoumoustaphadioufl3gl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADK_l9_hFaNwoyMSvFL7wvNOlYGCRbfZ0',
    appId: '1:412192105999:web:4ca7414063d305b855e57a',
    messagingSenderId: '412192105999',
    projectId: 'projetflutter-2860b',
    authDomain: 'projetflutter-2860b.firebaseapp.com',
    storageBucket: 'projetflutter-2860b.firebasestorage.app',
    measurementId: 'G-FGPCNC2WQQ',
  );
}
